### ISSUE TITLE
Get the standalone build working with mpi-serial which could allow the cesm-coupling branch to unite with the main branch

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/mizuRoute#212]
@nmizukami worked on this afternoon. In the latest version the standalone build doesn't work with mpi-serial. The problem we saw was that PIO needs to be linked to mpi-serial and use it (rather than mpi).

**Comment by ekluzek** [comment]
Mariana noted that the NUOPC version of CESM doesn't use the MCT mpi-serial, but uses the ESMF version of mpi-serial. So we should look into using the ESMF mpi-serial capability. Although I'm concerned that would mean we'd have to require the user to build ESMF and link to it. And that's sounds worse than using the MCT mpi-serial version.

**Comment by ekluzek** [comment]
I pushed some changes to get this working in the cesm-coupling branch in @nmizukami fork.

**Comment by ekluzek** [comment]
I think using the mpi-serial directory under mct in the externals is still the right way to go. But, talking with Mariana she did point out some caveats that we should be aware of. CESM will eventually stop support of MCT, so it's possible after that point the standalone build might run into trouble. Hopefully, there will still be support for MCT itself and for the standalone build we continue to be able to use it. Alternatively, stopping at a fixed version of MCT might be a possibility that works for some time going forward as well. I think these paths should work for at least a few years for going forward. If it does become a problem down the road likely the solution will be to require build ESMF and link to it's mpiuni version. And/or adopt a different MPI serial library of some sort that we find out there.

**Comment by nmizukami** [comment]
Getting back to this.

Try updating PIO version from 2_5_4 to 2_5_7 and cime version from 6.0.3 to 6.0.75, but did not fixed.

**Comment by ekluzek** [comment]
Since we found that mpi-serial isn't required with modern MPI libraries anymore. You can build with MPI and then run it as serial.

**Comment by ekluzek** [comment]
We now figure the standalone build can link to a full MPI library (which is standard on all HPC systems and can be easily installed on smaller systems). So closing as a wontfix.

**Comment by nmizukami** [comment]
wonfix because we don't need mpi-serial and this library build is removed now see #461
